Split vulnerability columns into their own table
sapcc/keppel pull request #160
Opened 2022-12-14 15:12 UTC by SuperSandro2000

2022-12-15 13:23 UTC, majewsky commented
@SuperSandro2000 asked me to take a look why `TestCheckVulnerabilitiesForNextManifestWithError` is failing right now.

The root cause is that the test does not step the clock after `image.MustUpload`. Since the `vulnCheckSelectQuery` looks for vuln_info entries with `v.next_check_at < $1` (where `$1` is the current time), the uploaded image does not match. I suggest changing this to `v.next_check_at <= $1`.

2022-12-15 14:31 UTC, majewsky requested changes
My overall impression is good, tough I do have a fair amount of notes. As usual, this is the broad sweep. I will do another more detailed review once these points are addressed.

2023-01-05 15:43 UTC, SuperSandro2000 commented on internal/keppel/models.go
> +	}
Turns out I already fixed this and the code is no longer needed.

2023-01-06 12:49 UTC, SuperSandro2000 commented
Fixed all the comments you had.

2023-01-06 14:21 UTC, majewsky requested changes
The fine sweep.

2023-01-06 14:21 UTC, majewsky commented on internal/tasks/manifests_test.go
> +	`, image.Layers[0].Digest, image.Manifest.Digest, s.Clock.Now().Add(2*time.Minute).Unix())
`%[1]s` is never used here, so it can be removed from the arg list.

2023-01-06 14:21 UTC, majewsky commented on internal/api/keppel/fixtures/delete-account-000.sql
> +INSERT INTO manifests (repo_id, digest, media_type, size_bytes, pushed_at, validated_at, validation_error_message, last_pulled_at, labels_json, gc_status_json, min_layer_created_at, max_layer_created
More manifests without vuln_info.

2023-01-09 09:58 UTC, majewsky approved these changes

2023-01-09 09:58 UTC, merged