Convert SweepBlobMounts to jobloop
sapcc/keppel pull request #234
Opened 2023-06-01 13:35 UTC by SuperSandro2000

2023-06-02 12:18 UTC, majewsky requested changes

2023-06-02 12:18 UTC, majewsky commented on internal/tasks/manifests.go
>  	if err != nil {
The ProcessTask function should not repeat the discovery query.

2023-06-09 11:24 UTC, majewsky requested changes

2023-06-09 11:24 UTC, majewsky commented on internal/tasks/manifests.go
> +				Help: "Counter for blob validations.",
There's a copy-paste error here, which now makes me concerned there's going to be more copy-paste errors elsewhere. Please have another look.

2023-06-15 14:57 UTC, majewsky approved these changes
I pushed one more commit to clean up the naming of functions and the references to those names throughout docstrings and comments. If this looks good to you, please go ahead with the merge.

2023-06-16 11:34 UTC, SuperSandro2000 commented
I was so focused on converting to the new library that I totally overlooked that those names are not that great. Thanks for cleaning up!

2023-06-16 11:34 UTC, merged